name: ${name}
version: ${version}
description: ${description}
load: POSTWORLD
api-version: ${api}
author: Hugo B.

main: ${group}.${artifact}.${main}

libraries:
  - "at.hugob.plugin.library:command:1.1.0"
  - "at.hugob.plugin.library:gui:0.0.1"
  - "at.hugob.plugin.library:config:1.1.2"
  - "at.hugob.plugin.library:database:1.0.0"

softdepend:
  - Essentials
  - ChestShop
  - BeastWithdraw
  #  - DeluxeSellWands
  - MoneyFromMobs
  - ShopGUIPlus

permissions:
  tl.command.help:
    description: allows access to the /tl help command
  tl.admin.reload:
    description: allows access to the /tl reload command
  tl.admin.version:
    description: allows access to the /tl version command
  tl.command.list:
    description: allows access to the /tl list command
  tl.command.view:
    description: allows access to the /tl view command
  tl.command.menu:
    description: allows access to the /tlm command
  tl.commands:
    description: allows access to all normal /tl commands
    children:
      tl.command.list: true
      tl.command.menu: true
      tl.command.help: true
  tl.admins:
    description: allows access to all /tl commands
    children:
      tl.commands: true
      tl.command.view: true
      tl.command.reload: true
      tl.command.version: true